apiVersion: v1
clusters:
- cluster:
    server: https://api.justcloud.skydays.ctf:8443
    insecure-skip-tls-verify: true
  name: cloud-k8s-cluster
contexts:
- context:
    cluster: cloud-k8s-cluster
    namespace: default
    user: guest-sa
  name: cloud-k8s-context
current-context: cloud-k8s-context
kind: Config
preferences: {}
users:
- name: guest-sa
  user:
    token: "dummy-bearer-token-12345"
