version: '3.8'

services:
  # 1. VERİTABANI SERVİSİ (PostgreSQL)
  db:
    image: postgres:15
    container_name: spatify_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lucario
      POSTGRES_DB: skydays
    ports:
      - "5432:5432"
    volumes:
      # Verilerin kalıcı olması için (Named Volume)
      - postgres_data:/var/lib/postgresql/data
      # Tabloları otomatik oluşturmak için (Host Mount)
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. UYGULAMA SERVİSİ (Node.js)
  app:
    build: .
    container_name: spatify_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: lucario
      DB_DATABASE: skydays

# GENEL VOLUMES TANIMI
# Burası sadece yukarıda kullanılan isimleri Docker'a tanıtır.
volumes:
  postgres_data: