server {
    listen 80;
    server_name localhost;

    # Her şeyi düz metin olarak sun
    default_type text/plain;

    location / {
        root /usr/share/nginx/html;
        
        # Eğer oyuncu dizin isterse (örn: /latest/meta-data/),
        # Nginx otomatik olarak o dizindeki index.html dosyasını okuyup metin olarak basar.
        index index.html;
        
        # Dizin listelemeyi (autoindex) kapalı tutuyoruz ki 
        # sadece bizim belirlediğimiz index.html dosyaları görünsün.
        autoindex off; 
    }
}
